name: KAUST VCC Visualization
title: KAUST High-Performance Visualization Group
collections: 
  research:
    output: true
    permalink: /:collection/:title/
  people:
    output: true
    permalink: /:collection/:title/